### ISSUE TITLE
Try mdbx

### ISSUE THREAD

**Issue by tieugene** [tieugene/kvtest#44]
https://github.com/erthink/libmdbx
~~macOS~~, ~~F34~~

**Comment by tieugene** [comment]
Too immature [yet](https://github.com/erthink/libmdbx/issues/197)

**Comment by erthink** [comment]
> Too immature [yet](https://github.com/erthink/libmdbx/issues/197)

LOL, [RTFM](https://github.com/erthink/libmdbx#source-code-embedding) ;-)

**Comment by erthink** [comment]
Another option is just to use [ioarena](https://github.com/pmwkaa/ioarena).

**Comment by tieugene** [comment]
> > Too immature [yet](https://github.com/erthink/libmdbx/issues/197)
> 
> LOL, [RTFM](https://github.com/erthink/libmdbx#source-code-embedding) ;-)

[RTFM](url): "TODO: ...Packages for ..., **Fedora/RHEL**"
